version: '3.8'
services:
  alma8:
    image: perfsonar/unibuild-alma8:latest
    build:
      context: ../
      dockerfile: ./docker-envs/Dockerfile-alma8
      network: host
    network_mode: "host"
    volumes:
      -  .:/app
  centos7:
    image: perfsonar/unibuild-centos7:latest
    build:
      context: ../
      dockerfile: ./docker-envs/Dockerfile-centos7
      network: host
    network_mode: "host"
    volumes:
      - .:/app
  debian10:
    image: perfsonar/unibuild-debian10:latest
    build:
      context: ../
      dockerfile: ./docker-envs/Dockerfile-debian10
      network: host
    network_mode: "host"
    volumes:
      -  .:/app
